import { createElement } from 'lwc';
import Sat_p2cStudentSearchParent from 'c/sat_p2cStudentSearchParent';

describe('c-sat-p2-c-student-search-parent', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-sat-p2-c-student-search-parent', {
            is: Sat_p2cStudentSearchParent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});