public class PrimativeDataTypeDemo2 {
    public void print1(){
        ID id1 = '0017Q00000QeyGOQAZ';
        system.debug('print id= ' + id1);

        Object obj1 = 'This is a string';
        Object obj2 = 15;
        Object obj3 = '0017Q00000QeyGOQAZ';
        Object obj4 = true;

        system.debug('obj1 = ' + obj1);
        system.debug('obj2 = ' + obj2);
        system.debug('obj3 = ' + obj3);
        system.debug('obj4 = ' + obj4);
    }
}
