Candidates.printCandidateInfo();

Candidates.CompanyName = 'Softinnovas';

Candidates c1 = new Candidates();
c1.Name = 'Jerry';
c1.Gender = 'Male';
c1.printCandidate();

Candidates c2 = new Candidates();
c2.Name = 'Elain';
c2.Gender = 'Female';
c2.printCandidate();

Candidates.CompanyName = 'Vandley';
Candidates c3 = new Candidates();
c3.Name = 'George';
c3.Gender = 'Male';
c3.printCandidate();




