Map<string, email_domain__mdt> allEmailDomains = email_domain__mdt.getAll();
System.debug(allEmailDomains);

{
    Gmail=Email_Domain__mdt:{Domain__c=Gmail, Label=Gmail, MasterLabel=Gmail, Language=de, QualifiedApiName=Gmail, Id=m007Q0000002CHW, DeveloperName=Gmail, NamespacePrefix=null}, 
    
    hotmail=Email_Domain__mdt:{Domain__c=hotmail, Label=hotmail, MasterLabel=hotmail, Language=de, QualifiedApiName=hotmail, Id=m007Q0000002CHb, DeveloperName=hotmail, NamespacePrefix=null}
    }